CREATE TABLE thread (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    category VARCHAR(63) NOT NULL,
    title VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE post (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    thread_id INTEGER NOT NULL,
    username VARCHAR(50) NOT NULL,
    content VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (thread_id) REFERENCES thread(id),
    FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE attachment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    filename VARCHAR(255) DEFAULT NULL,
    content_type VARCHAR(255) DEFAULT NULL,
    content BLOB DEFAULT NULL,
    post_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES post(id) 
);