CREATE TABLE poll (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE response (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    poll_id INTEGER NOT NULL,
    content VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES poll(id)
);

CREATE TABLE vote (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    response_id INTEGER NOT NULL,
    username VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (response_id) REFERENCES response(id),
    FOREIGN KEY (username) REFERENCES users(username)
);